#!/bin/sh

start()
{
    ln -s /proc/self/fd /dev/fd
}

stop()
{
    rm /dev/fd
}

case "${1}" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
