#!/bin/sh

start()
{
    ifconfig lo up
    ifconfig eth0 up

    mac=`ifconfig eth0 | grep ether | awk '{print $2}'`
    ip3=`echo ${mac} | cut -f3 -d:`
    ip2=`echo ${mac} | cut -f4 -d:`
    ip1=`echo ${mac} | cut -f5 -d:`
    ip0=`echo ${mac} | cut -f6 -d:`

    # remove leading '0' (if any)
    ip3=$((10#${ip3}))
    ip2=$((10#${ip2}))
    ip1=$((10#${ip1}))
    ip0=$((10#${ip0}))

    ip="${ip3}.${ip2}.${ip1}.${ip0}"
    bip="${ip3}.${ip2}.${ip1}.255"
    rip="${ip3}.${ip2}.${ip1}.1"


    ifconfig eth0 ${ip}
    ifconfig eth0 netmask 255.255.255.0
    ifconfig eth0 broadcast ${bip}
    route add default gw ${rip}

    echo "Configured to IP: ${ip}"
}

stop()
{
    ifconfig eth0 down
}

case "${1}" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
